apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swarmscribe-leader.fullname" . }}
  labels:
    {{- include "swarmscribe-leader.labels" . | nindent 4 }}
data:
  {{- include "swarmscribe-leader.settings" . | nindent 2 }}
