apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swarmscribe-console.fullname" . }}
  labels:
    {{- include "swarmscribe-console.labels" . | nindent 4 }}
data:
  {{- include "swarmscribe-console.settings" . | nindent 2 }}
