{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "swarmscribe-console.fullname" . }}
  labels:
    {{- include "swarmscribe-console.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "swarmscribe-console.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: console
{{- end }}
