"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 21:53:21.339372

"""
import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=True),
    sa.Column('subject_id', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('pool', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('settings_profiles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device', sa.String(length=8), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('compute_type', sa.String(length=32), nullable=False),
    sa.Column('temperatures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storage_locations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('backend', sa.String(length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_ref', sa.String(length=200), nullable=True),
    sa.Column('input_prefix', sa.Text(), nullable=False),
    sa.Column('output_location_id', sa.Uuid(), nullable=True),
    sa.Column('output_prefix', sa.Text(), nullable=False),
    sa.Column('pool', sa.String(length=100), nullable=False),
    sa.Column('required_device', sa.String(length=8), nullable=False),
    sa.Column('scan_interval_s', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('vocabulary_version', sa.Integer(), nullable=False),
    sa.Column('vocabulary_hash', sa.String(length=64), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['output_location_id'], ['storage_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vocabularies',
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'version')
    )
    op.create_table('followers',
    sa.Column('pool', sa.String(length=100), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('join_token_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['join_token_id'], ['join_tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_hash')
    )
    op.create_table('recordings',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('source_version', sa.String(length=200), nullable=False),
    sa.Column('consent', sa.String(length=16), nullable=False),
    sa.Column('consent_pattern', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('missing', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['storage_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'key')
    )
    op.create_table('jobs',
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('source_version', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('pool', sa.String(length=100), nullable=False),
    sa.Column('required_device', sa.String(length=8), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Uuid(), nullable=True),
    sa.Column('leased_by', sa.Uuid(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vocabulary_version', sa.Integer(), nullable=True),
    sa.Column('settings_profile_id', sa.Uuid(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outputs_flagged_for_deletion', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leased_by'], ['followers.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['settings_profile_id'], ['settings_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['state', 'pool', 'priority', 'created_at'], unique=False)
    op.create_table('job_attempts',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('lease_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['followers.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_attempts_lease', 'job_attempts', ['job_id', 'lease_id'], unique=False)
    op.create_table('job_results',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('txt_sha256', sa.String(length=64), nullable=False),
    sa.Column('srt_sha256', sa.String(length=64), nullable=False),
    sa.Column('segments_sha256', sa.String(length=64), nullable=False),
    sa.Column('duration_s', sa.Double(), nullable=True),
    sa.Column('engine_version', sa.String(length=50), nullable=True),
    sa.Column('vocabulary_terms_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('corrections_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('low_confidence_words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###

    profiles = sa.table(
        "settings_profiles",
        sa.column("id", sa.Uuid),
        sa.column("name", sa.String),
        sa.column("device", sa.String),
        sa.column("model", sa.String),
        sa.column("compute_type", sa.String),
        sa.column("temperatures", postgresql.JSONB),
    )
    op.bulk_insert(
        profiles,
        [
            {
                "id": uuid.UUID("5e7f2a3c-0d1b-4c5e-9f00-000000000001"),
                "name": "cuda",
                "device": "cuda",
                "model": "large-v3",
                "compute_type": "float16",
                "temperatures": [0.0, 0.2, 0.4],
            },
            {
                "id": uuid.UUID("5e7f2a3c-0d1b-4c5e-9f00-000000000002"),
                "name": "cpu",
                "device": "cpu",
                "model": "distil-large-v3",
                "compute_type": "int8",
                "temperatures": [0.0, 0.2, 0.4],
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_results')
    op.drop_index('ix_job_attempts_lease', table_name='job_attempts')
    op.drop_table('job_attempts')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('recordings')
    op.drop_table('followers')
    op.drop_table('vocabularies')
    op.drop_table('storage_locations')
    op.drop_table('settings_profiles')
    op.drop_table('join_tokens')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
